project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  site-url: https://www.jianqihuang.com
  title: "Jianqi"
  twitter-card: 
    creator: "@jianqih"
  repo-url: https://github.com/jianqih/jianqih.github.io
  repo-actions: [edit, issue]
  open-graph: true
  # sidebar: 
  #   collapse-level: 1
  favicon: fav.png
  navbar:
    background: dark
    foreground: light
    left:
      - href: cv/CV.pdf
        text: CV
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: talks.qmd
        text: Talks & Workshops
      - href: post.qmd
        text: Posts
      - text: More
        menu: 
        - href: misc.qmd
        - href: RS.qmd
  page-footer: 
    # background: light
    left: "Copyright 2023, Jianqi Huang"

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    highlight-style: tango
    from: markdown+emoji
    # page-layout: full